### ISSUE TITLE
Register values are not visible on Windows console

### ISSUE THREAD

**Issue by alvaro-cuesta** [Hackchain/hackchain-debugger#1]
The values are there, but the foreground and background colors seem to be the same. The `rX:` labels are visible though.

**Comment by indutny** [comment]
Please give a try to 3.0.4, hopefully it is better now.

**Comment by alvaro-cuesta** [comment]
The registers are now visible, thanks.

As a side effect, I just discovered the {q, f5, f10} "buttons" had labels. They were invisible too. Now those labels are visible, but the buttons themselves are gone (black on black).

**Comment by indutny** [comment]
@alvaro-cuesta please give it one more try. This time version is: 3.0.2.

**Comment by alvaro-cuesta** [comment]
Fixed, thanks!
